version: '3.7'

services:
  taiga-db:
    image: postgres:12-alpine  # Use a smaller Alpine-based Postgres
    platform: linux/amd64
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: taigauser
      POSTGRES_PASSWORD: password123
    volumes:
      - taiga-db-data:/var/lib/postgresql/data
    networks:
      - taiga
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"

  taiga-back:
    image: taigaio/taiga-back:latest
    platform: linux/amd64
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: taigauser
      POSTGRES_PASSWORD: password123
      POSTGRES_HOST: taiga-db
      TAIGA_SECRET_KEY: "example-secret-key"
      PUBLIC_REGISTER_ENABLED: "True"
      ENABLE_TELEMETRY: "False"
    networks:
      - taiga
    depends_on:
      - taiga-db
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"

  taiga-front:
    image: taigaio/taiga-front:latest
    platform: linux/amd64
    environment:
      TAIGA_URL: "http://localhost:9000"
      TAIGA_WEBSOCKETS_URL: "ws://localhost:9000"
    networks:
      - taiga
    depends_on:
      - taiga-back
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.3"

  taiga-events-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    platform: linux/amd64
    environment:
      RABBITMQ_DEFAULT_USER: taiga
      RABBITMQ_DEFAULT_PASS: taiga
    hostname: "taiga-rabbitmq"
    volumes:
      - taiga-events-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - taiga
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.3"

  taiga-gateway:
    image: nginx:1.19-alpine
    platform: linux/amd64
    ports:
      - "9000:80"
    volumes:
      - ./taiga-gateway/taiga.conf:/etc/nginx/conf.d/default.conf
    networks:
      - taiga
    depends_on:
      - taiga-front
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: "0.2"

volumes:
  taiga-db-data:
  taiga-events-rabbitmq-data:

networks:
  taiga:
